package ordenpizza;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author alein
 */
public class JFrameOrden extends javax.swing.JFrame {

    /**
     * Creates new form JFrameOrden
     */
    public JFrameOrden() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSize = new javax.swing.ButtonGroup();
        buttonGroupCubierta = new javax.swing.ButtonGroup();
        buttonGroupPedido = new javax.swing.ButtonGroup();
        jPanelSize = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonPeque = new javax.swing.JRadioButton();
        jRadioButtonMed = new javax.swing.JRadioButton();
        jRadioButtonGrand = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBoxQuesoEx = new javax.swing.JCheckBox();
        jCheckBoxCebolla = new javax.swing.JCheckBox();
        jCheckBoxChamp = new javax.swing.JCheckBox();
        jCheckBoxAceitunas = new javax.swing.JCheckBox();
        jCheckBoxPVerde = new javax.swing.JCheckBox();
        jCheckBoxTomates = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonCDel = new javax.swing.JRadioButton();
        jRadioButtonCGru = new javax.swing.JRadioButton();
        jButtonQuit = new javax.swing.JButton();
        jButtonOrden = new javax.swing.JButton();
        jButtonNew = new javax.swing.JButton();
        jRadioButtonMesa = new javax.swing.JRadioButton();
        jRadioButtonDelivery = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tamaño");

        buttonGroupSize.add(jRadioButtonPeque);
        jRadioButtonPeque.setText("Pequeña");
        jRadioButtonPeque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPequeActionPerformed(evt);
            }
        });

        buttonGroupSize.add(jRadioButtonMed);
        jRadioButtonMed.setText("Mediana");

        buttonGroupSize.add(jRadioButtonGrand);
        jRadioButtonGrand.setText("Grande");

        javax.swing.GroupLayout jPanelSizeLayout = new javax.swing.GroupLayout(jPanelSize);
        jPanelSize.setLayout(jPanelSizeLayout);
        jPanelSizeLayout.setHorizontalGroup(
            jPanelSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSizeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSizeLayout.createSequentialGroup()
                        .addGroup(jPanelSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSizeLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jRadioButtonPeque, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSizeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonMed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonGrand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanelSizeLayout.setVerticalGroup(
            jPanelSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonPeque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonMed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonGrand)
                .addContainerGap())
        );

        jLabel2.setText("Ingredientes");

        jCheckBoxQuesoEx.setText("Queso Extra");

        jCheckBoxCebolla.setText("Cebolla");

        jCheckBoxChamp.setText("Champiñones");

        jCheckBoxAceitunas.setText("Aceitunas");

        jCheckBoxPVerde.setText("Pimentón Verde");

        jCheckBoxTomates.setText("Tomates");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBoxChamp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBoxQuesoEx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(4, 4, 4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBoxAceitunas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBoxTomates, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jCheckBoxCebolla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(48, 48, 48))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jCheckBoxPVerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(21, 21, 21)))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxQuesoEx)
                    .addComponent(jCheckBoxCebolla))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxChamp)
                    .addComponent(jCheckBoxPVerde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxAceitunas)
                    .addComponent(jCheckBoxTomates))
                .addContainerGap())
        );

        jLabel3.setText("Tipo de Cubierta");

        buttonGroupCubierta.add(jRadioButtonCDel);
        jRadioButtonCDel.setText("Cubierta Delgada");

        buttonGroupCubierta.add(jRadioButtonCGru);
        jRadioButtonCGru.setText("Cubierta Gruesa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(jRadioButtonCDel)
                    .addComponent(jRadioButtonCGru))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCDel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCGru)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonQuit.setText("Salir");
        jButtonQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitActionPerformed(evt);
            }
        });

        jButtonOrden.setText("Ordenar Pizza");
        jButtonOrden.setToolTipText("Seleccione el tamaño, Ingredientes, Tipo de Cubierta y Tipo de Pedido para continuar.");
        jButtonOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrdenActionPerformed(evt);
            }
        });

        jButtonNew.setText("Nuevo");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        buttonGroupPedido.add(jRadioButtonMesa);
        jRadioButtonMesa.setText("Para Mesa");

        buttonGroupPedido.add(jRadioButtonDelivery);
        jRadioButtonDelivery.setText("Delivery");

        jLabel4.setText("Tipo de Pedido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonOrden)
                                .addGap(143, 143, 143)
                                .addComponent(jButtonNew))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonQuit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonMesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonDelivery)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOrden)
                    .addComponent(jButtonNew)
                    .addComponent(jButtonQuit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonPequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPequeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPequeActionPerformed

    private void jButtonOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrdenActionPerformed
        
        
        double precio=0;
        String message ="Detalles de venta\nTamaño de Pizza\n";
        int resp = 0;
        
  
        if (jRadioButtonPeque.isSelected()) {
            precio+=20;
            message+="Tamaño: Pequeña\n";
        }
        if (jRadioButtonMed.isSelected()) {
            precio+=30;
            message+="Tamaño: Mediana\n";
        }
        if (jRadioButtonGrand.isSelected()) {
            precio+=40;
            message+="Tamaño: Grande\n";
        }
        message+="Tipo de Cubierta\n";
        if (jRadioButtonCDel.isSelected()) {
            precio+=5;
            message+="Cubierta: "+jRadioButtonCDel.getText()+"\n";
        }
        if (jRadioButtonCGru.isSelected()) {
            precio+=7;
            message+="Cubierta: "+jRadioButtonCGru.getText()+"\n";
        }
        message+="Ingredientes EXTRAS\n";
        if (jCheckBoxQuesoEx.isSelected()) {
            precio+=12.5;
            message+=jCheckBoxQuesoEx.getText()+"\n";
        }
        if (jCheckBoxChamp.isSelected()) {
            precio+=20;
            message+=jCheckBoxChamp.getText()+"\n";
        }
        if (jCheckBoxAceitunas.isSelected()) {
            precio+=10;
            message+=jCheckBoxAceitunas.getText()+"\n";
        }
        
        if (jCheckBoxCebolla.isSelected()) {
            precio+=2.5;
            message+=jCheckBoxCebolla.getText()+"\n";
        }
        
        if (jCheckBoxPVerde.isSelected()) {
            precio+=5;
            message+=jCheckBoxPVerde.getText()+"\n";
        }
        
        if (jCheckBoxTomates.isSelected()) {
            precio+=7.5;
            message+=jCheckBoxTomates.getText()+"\n";
        }
        
        message+="Tipo de pedido";
        if (jRadioButtonMesa.isSelected()) {
            precio+=2.5;
            message+="Pedido a mesa.";
        }
        if (jRadioButtonDelivery.isSelected()) {
            precio+=10;
            message+="Pedido Delivery";
        }
        DecimalFormat f2 = new DecimalFormat("0.00");
        resp = JOptionPane.showConfirmDialog(null, message,"Verifique su Orden",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (resp==JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Su pizza cuesta: S/."+f2.format(precio),"Boleta de pago",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonOrdenActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        buttonGroupCubierta.clearSelection();
        buttonGroupSize.clearSelection();
        buttonGroupPedido.clearSelection();
        jCheckBoxAceitunas.setSelected(false);
        jCheckBoxCebolla.setSelected(false);
        jCheckBoxChamp.setSelected(false);
        jCheckBoxPVerde.setSelected(false);
        jCheckBoxQuesoEx.setSelected(false);
        jCheckBoxTomates.setSelected(false);
        jRadioButtonPeque.grabFocus();
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitActionPerformed
        int resp;
        resp = JOptionPane.showConfirmDialog(null, "Desea salir de la aplicación?","Aviso al Cliente",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (resp==JOptionPane.YES_OPTION) {
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Sigue en la aplicación.");
        }      
    }//GEN-LAST:event_jButtonQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameOrden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCubierta;
    private javax.swing.ButtonGroup buttonGroupPedido;
    private javax.swing.ButtonGroup buttonGroupSize;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonOrden;
    private javax.swing.JButton jButtonQuit;
    private javax.swing.JCheckBox jCheckBoxAceitunas;
    private javax.swing.JCheckBox jCheckBoxCebolla;
    private javax.swing.JCheckBox jCheckBoxChamp;
    private javax.swing.JCheckBox jCheckBoxPVerde;
    private javax.swing.JCheckBox jCheckBoxQuesoEx;
    private javax.swing.JCheckBox jCheckBoxTomates;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelSize;
    private javax.swing.JRadioButton jRadioButtonCDel;
    private javax.swing.JRadioButton jRadioButtonCGru;
    private javax.swing.JRadioButton jRadioButtonDelivery;
    private javax.swing.JRadioButton jRadioButtonGrand;
    private javax.swing.JRadioButton jRadioButtonMed;
    private javax.swing.JRadioButton jRadioButtonMesa;
    private javax.swing.JRadioButton jRadioButtonPeque;
    // End of variables declaration//GEN-END:variables
}
